name: Quality Checks

on: [push]

jobs:
  static-analysis:
    name: Run static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Setup base environment
        uses: ./.github/actions/base-environment

      - name: Run static analysis
        run: composer check:static

  code-style:
    name: Run style check
    runs-on: ubuntu-latest
    steps:
      - name: Setup base environment
        uses: ./.github/actions/base-environment

      - name: Run static analysis
        run: composer check:style

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup base environment
        uses: ./.github/actions/base-environment

      - name: Run static analysis
        run: composer check:tests
